require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "config/**/*"
    - "bin/**/*"
    - "db/structure.sql"
    - "db/schema.rb"

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Naming/VariableNumber:
  EnforcedStyle: snake_case
  AllowedIdentifiers: ['auth0']

RSpec/ContextWording:
  Prefixes:
    - when
    - and

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/AlignLeftLetBrace:
  Enabled: true

RSpec/StubbedMock:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 20

RSpec/SpecFilePathFormat:
  Exclude:
    - "spec/requests/**/*"

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - "spec/**/*"

Rails/NotNullColumn:
  Enabled: false
